name: Deploy FFC
on:  [push]
paths:
  - bin
  - lambdas
  - lib
  - package-lock.json

env:
  AWS_REGION: eu-west-1
  CDK_DEFAULT_REGION: eu-west-1
  ACCOUNT_ID: 471458021033
  BUCKET_NAME: ffc-prod-photos-83640
  BUCKET_NAME_STAGING: ffc-stag-photos-83641


jobs:
  deploy:
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.FFC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install trigger dependencies
        run: cd lambdas/trigger && npm install

      - name: Deploy to Staging
        run: npm run deploy:staging
        env:
          TREE_API_URL: https://api-staging.thefutureforestcompany.com

      - name: Deploy to Prod if main
      if: github.ref == 'refs/heads/main'
      run: npm run deploy
      env:
          TREE_API_URL: https://api.thefutureforestcompany.com

      - name: Archive cdk output
        uses: actions/upload-artifact@v2
        with:
          name: cdk-out
          path: cdk/cdk.out
          retention-days: 30
